version: "3"
services:
  cron:
    build: ./cron
    restart: "always"
    volumes:
      - /var/log/crontainer:/var/log/crontainer
      - ./cron/crontabs:/etc/crontabs
      - ./mechanical_griot:/mechanical_griot